### PR TITLE
Remove use of wiki specific url syntax

### PR DESCRIPTION
**Pull request by seb128**
Neither github nor launchpad understand it

### CODE REVIEW

**Comment by seb128** [comment]
I end up deleting those parts every time I open a MIR request which is slighly annoying, I think it makes more sense to not have them since they don't have the intended effect. 

Note that there is a few extra use but those are in RULES sections which are usually not included so I didn't change those but I could if that's preferred

**Review by dviererbe — CHANGES_REQUESTED** [review]
I looked through the commit history and the `README.md` file was previously named `wiki.moinmoin` and formatted in the [MoinMoin](https://help.launchpad.net/HelpOnMoinWikiSyntax?action=show&redirect=SyntaxReference) Syntax.

This looks like one of the leftovers that was never removed/changed. If we remove/change this, than we should remove/change the other MoinMoin link occurrences too.

**Comment by slyon** [comment]
+1 with @dviererbe's improvements.

**Review by didrocks — APPROVED** [review]
Looks like straightfoward.

**Comment by setharnold** [comment]
+1 also with @dviererbe 's suggested changes

**Comment by dviererbe** [comment]
@seb128 Most of the work in documentation is simply noticing things like this. :) Can you (squash) merge my changes and than (force) push into your branch?

**Comment by seb128** [comment]
> @seb128 Most of the work in documentation is simply noticing things like this. :) Can you (squash) merge my changes and than (force) push into your branch?

I did that now, thanks!

**Review by slyon — APPROVED** [review]
lgtm

**Pull request merged**
